name: Update README with Recent Activity

on:
  schedule:
    - cron: "0 */6 * * *" # Updates every 6 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "📊 Updated README with recent activity"
          MAX_LINES: 5
