name: Update README with Recent Activity

on:
  schedule:
    - cron: "0 */6 * * *" # Every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@v0.2.0
        with:
          COMMIT_MSG: "📊 Updated README with recent activity"
          MAX_LINES: 5
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
